# a make command that runs "gleam run -m gladvent run --year=2023 PARAM", where PARAM is a number passed to the make command
# Example: make run DAY=42
solve:
	@gleam run -m gladvent run --year=2023 $(DAY)